### ISSUE TITLE
integration: Yaml validation tutorial inconsistent with implementation

### ISSUE THREAD

**Issue by myitcv** [cue-lang/docs-and-content#61] opened 2024-02-19 16:26 UTC
Per https://github.com/cue-lang/cue/issues/1106

This should be fixed

**Comment by jpluscplusm** [comment] 2024-08-20 14:14
https://github.com/cue-lang/cue/issues/1106 points out a number of problems with the YAML Integrations page.
The singleton page at https://cuelang.org/docs/integration/ points its YAML readers to the revised page, now at https://cuelang.org/docs/concept/how-cue-works-with-yaml/. This page doesn't suffer from any of the problems the reporter experienced.

Additionally, the unexpected output the reporter mentioned when following https://cuelang.org/docs/tour/types/bottom/ and https://cuelang.org/docs/tour/types/numbers/ appears to have been caused by them using a mismatched version of the `cue` command, where their version didn't understand `cue eval -i`. The `-i` flag is now called out explicitly on first use in the tour, at https://cuelang.org/docs/tour/types/bottom/.

I'll put a note in https://github.com/cue-lang/cue/issues/1106, closing it.

**Closed by jpluscplusm** 2024-08-20 14:14 UTC
Labels: bug
